t12

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -105,36 +105,6 @@ jobs:
             pod install
 
       - run:
-          name: Generate Flutter Files
-          command: |
-            cd $PROJECT_DIR/..
-            # Flutter 빌드 전 Generated.xcconfig 생성을 위한 설정
-            flutter config --no-analytics
-            flutter clean
-            flutter pub get
-            
-            # iOS 빌드 파일 생성
-            flutter build ios --release --no-codesign
-            
-            # Generated.xcconfig 파일 확인
-            if [ ! -f "$PROJECT_DIR/Flutter/Generated.xcconfig" ]; then
-              echo "❌ ERROR: Generated.xcconfig not found after build"
-              exit 1
-            fi
-
-      - run:
-          name: Setup iOS Build Environment
-          command: |
-            cd $PROJECT_DIR
-            
-            # Release.xcconfig 파일이 Generated.xcconfig를 올바르게 참조하도록 수정
-            echo '#include "Flutter/Generated.xcconfig"' > Flutter/Release.xcconfig
-            echo '#include "Flutter/Generated.xcconfig"' > Flutter/Debug.xcconfig
-            
-            # CocoaPods 설치
-            pod install
-
-      - run:
           name: Extract Workspace and Scheme
           command: |
             cd $PROJECT_DIR
@@ -237,6 +207,37 @@ jobs:
             
             # CircleCI의 빌드 번호를 사용하여 앱 빌드 번호 설정
             xcrun agvtool new-version -all $CIRCLE_BUILD_NUM
+
+
+      - run:
+          name: Generate Flutter Files
+          command: |
+            cd $PROJECT_DIR/..
+            # Flutter 빌드 전 Generated.xcconfig 생성을 위한 설정
+            flutter config --no-analytics
+            flutter clean
+            flutter pub get
+            
+            # iOS 빌드 파일 생성
+            flutter build ios --release --no-codesign
+            
+            # Generated.xcconfig 파일 확인
+            if [ ! -f "$PROJECT_DIR/Flutter/Generated.xcconfig" ]; then
+              echo "❌ ERROR: Generated.xcconfig not found after build"
+              exit 1
+            fi
+
+      - run:
+          name: Setup iOS Build Environment
+          command: |
+            cd $PROJECT_DIR
+            
+            # Release.xcconfig 파일이 Generated.xcconfig를 올바르게 참조하도록 수정
+            echo '#include "Flutter/Generated.xcconfig"' > Flutter/Release.xcconfig
+            echo '#include "Flutter/Generated.xcconfig"' > Flutter/Debug.xcconfig
+            
+            # CocoaPods 설치
+            pod install
 
       - run:
           name: 빌드
